version: "3.9"
services:
  grafana:
    image: grafana/grafana:8.3.4
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/etc/grafana/provisioning-dashboards
  prometheus:
    image: quay.io/prometheus/prometheus:v2.33.1
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  node-exporter:
    image: quay.io/prometheus/node-exporter:v1.3.1
  # influxdb:
  #   image: influxdb:2.1.1
  #   environment:
  #     - DOCKER_INFLUXDB_INIT_MODE=setup
  #     - DOCKER_INFLUXDB_INIT_USERNAME=admin
  #     - DOCKER_INFLUXDB_INIT_PASSWORD=adminadmin
  #     - DOCKER_INFLUXDB_INIT_ORG=strrl
  #     - DOCKER_INFLUXDB_INIT_BUCKET=poc
  #   ports:
  #     - "8086:8086"
  # telegraf:
  #   image: telegraf:1.21.3